# This is a basic workflow to help you get started with Actions

name: Doxygen generation

# Controls when the workflow will run
on:
  workflow_dispatch:
jobs:
  doxygen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo Generating documentation using doxygen.
      - name: Doxygen Action
        # You may pin to the exact commit or the version.
        # uses: mattnotmitt/doxygen-action@e13253538ce85a582a7b09338d541740c0f8d923
        uses: mattnotmitt/doxygen-action@1.9.4
        with:
        # Path to Doxyfile
          doxyfile-path: ./Doxyfile
        # Working directory
          working-directory: .
        # Generate latex documentation
          enable-latex: false
        # Extra alpine packages for the build environment
        #  additional-packages:
      - uses: actions/upload-artifact@v3
        with:
          name: doxygenBuild
          path: Doxygen/html # or path/to/artifact
