name: Gource Action
on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  action:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
        
      - name: 'Gource Action'
        uses: nbprojekt/gource-action@v1
        with:
          gource_title: 'SafeHaven GitHub'
          gource_time_scale: 1
          gource_resolution: '1080p'
          gource_fps: 60
          gource_seconds_per_day: 10
          gource_bloom_multiplier: 0.3
          gource_bloom_intensity: 0.3

      - name: 'Upload gource video'
        uses: actions/upload-artifact@v3
        with:
          name: Gource
          path: ./gource/gource.mp4
